sonar.projectKey=eventhub-backend
sonar.projectName=EventHub Backend
sonar.sources=src
sonar.tests=src/tests
sonar.test.inclusions=src/tests/**/*.test.ts
sonar.exclusions=src/tests/**,src/prisma/**,dist/**,coverage/**
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
